package com.shoppingagent.agent;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.shoppingagent.search.model.Product;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;

import java.util.List;

/**
 * Module 5.11 — structured response shape the future frontend consumes.
 * {@code message} is always a plain-language string generated by templating
 * over real data (never further LLM embellishment of facts — see 5.12), so it
 * never contains a hallucinated price/rating/etc.
 */
@Getter
@Builder
@AllArgsConstructor
@JsonInclude(JsonInclude.Include.NON_NULL)
public class AgentResponse {

    private String conversationId;
    private AssistantMessage message;
    private AgentResponseStatus status;
    private List<Product> products;

    @Getter
    @Builder
    @AllArgsConstructor
    public static class AssistantMessage {
        @Builder.Default
        private String role = "ASSISTANT";
        private String content;
    }
}
