package com.shoppingagent.agent;

import com.shoppingagent.ai.ChatTurn;
import com.shoppingagent.ai.ShoppingAgentService;
import com.shoppingagent.ai.exception.AiServiceException;
import com.shoppingagent.ai.intent.ShoppingIntent;
import com.shoppingagent.ai.model.RequirementAnalysis;
import com.shoppingagent.ai.model.ShoppingQuery;
import com.shoppingagent.search.ProductSearchService;
import com.shoppingagent.search.exception.SearchException;
import com.shoppingagent.search.model.Product;
import com.shoppingagent.search.model.SearchResult;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Service;

import java.util.List;

@Service
public class ShoppingChatOrchestrationServiceImpl implements ShoppingChatOrchestrationService {

    private static final Logger log = LoggerFactory.getLogger(ShoppingChatOrchestrationServiceImpl.class);

    private final ShoppingAgentService shoppingAgentService;
    private final ProductSearchService productSearchService;

    public ShoppingChatOrchestrationServiceImpl(ShoppingAgentService shoppingAgentService,
                                                 ProductSearchService productSearchService) {
        this.shoppingAgentService = shoppingAgentService;
        this.productSearchService = productSearchService;
    }

    @Override
    public AgentResponse handleUserMessage(String conversationId,
                                            List<ChatTurn> history,
                                            ShoppingQuery previousQuery,
                                            String latestUserMessage) {
        RequirementAnalysis analysis;
        try {
            analysis = shoppingAgentService.analyze(history, previousQuery, latestUserMessage);
        } catch (AiServiceException e) {
            log.warn("Shopping agent analysis failed for conversation {}: {}", conversationId, e.getMessage());
            return errorResponse(conversationId,
                    "I couldn't understand that request right now. Please try again.");
        }

        if (analysis.getIntent() == ShoppingIntent.PRODUCT_COMPARISON) {
            // Comparison/ranking logic belongs to Module 7 — not implemented yet.
            return clarificationResponse(conversationId,
                    "I can search for products for you, but side-by-side comparison isn't "
                            + "available yet. Want me to search for them individually instead?");
        }

        if (!analysis.isReadyToSearch()) {
            String question = analysis.getClarificationQuestion();
            return clarificationResponse(conversationId,
                    question != null ? question : "Could you share a bit more detail about what you're looking for?");
        }

        SearchResult searchResult;
        try {
            searchResult = productSearchService.search(analysis.getShoppingQuery());
        } catch (SearchException e) {
            log.warn("Product search failed for conversation {}: {}", conversationId, e.getMessage());
            return errorResponse(conversationId, e.getMessage());
        }

        List<Product> products = searchResult.getProducts();
        if (products.isEmpty()) {
            return AgentResponse.builder()
                    .conversationId(conversationId)
                    .status(AgentResponseStatus.NO_RESULTS)
                    .products(List.of())
                    .message(AgentResponse.AssistantMessage.builder()
                            .content("I couldn't find anything matching that. Want to try a different budget or brand?")
                            .build())
                    .build();
        }

        return AgentResponse.builder()
                .conversationId(conversationId)
                .status(AgentResponseStatus.PRODUCT_RESULTS)
                .products(products)
                .message(AgentResponse.AssistantMessage.builder()
                        .content(summarize(products))
                        .build())
                .build();
    }

    /**
     * Purely templated over real search data — never generated by the LLM — so
     * it can never state a fact the search layer didn't actually provide
     * (Module 5.12).
     */
    private String summarize(List<Product> products) {
        int count = products.size();
        if (count == 1) {
            return "I found 1 option matching your requirements.";
        }
        return "I found " + count + " options matching your requirements.";
    }

    private AgentResponse clarificationResponse(String conversationId, String question) {
        return AgentResponse.builder()
                .conversationId(conversationId)
                .status(AgentResponseStatus.CLARIFICATION)
                .products(List.of())
                .message(AgentResponse.AssistantMessage.builder().content(question).build())
                .build();
    }

    private AgentResponse errorResponse(String conversationId, String message) {
        return AgentResponse.builder()
                .conversationId(conversationId)
                .status(AgentResponseStatus.ERROR)
                .products(List.of())
                .message(AgentResponse.AssistantMessage.builder().content(message).build())
                .build();
    }
}
